[package]
name = "uncomment"
version = "2.0.0"
authors = ["Na'aman Hirschfeld <nhirschfeld@gmail.com>"]
description = "A CLI tool to remove comments from code using tree-sitter for accurate parsing"
edition = "2021"
keywords = ["comments", "cli", "tree-sitter", "ast"]
license = "MIT"
repository = "https://github.com/Goldziher/uncomment"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tree-sitter = "0.20.10"
tree-sitter-python = "0.20"
tree-sitter-javascript = "0.20"
tree-sitter-typescript = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-go = "0.20"
tree-sitter-java = "0.20"
tree-sitter-c = "0.20"
tree-sitter-cpp = "0.20"
tree-sitter-ruby = "0.20"
tree-sitter-json = "0.20"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
glob = "0.3"
ignore = "0.4"
anyhow = "1.0"
once_cell = "1.19"
regex = "1.10"

[dev-dependencies]
tempfile = "3.8"
pretty_assertions = "1.4"

[lib]
name = "uncomment"
path = "src/lib.rs"

[[bin]]
name = "uncomment"
path = "src/main.rs"
